name: Release - {{ APP_NAME | default('Application') }}

on:
  push:
    branches:
      - {{ RELEASE_BRANCHES | default('main') }}
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install semantic-release
      run: |
        npm install -g \
          semantic-release \
          @semantic-release/changelog \
          @semantic-release/git \
          @semantic-release/github \
          conventional-changelog-conventionalcommits
    
    - name: Verify commit messages
      run: |
        git log --format=%B -n 1 HEAD | grep -E '^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .+'
    
    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release
    
    - name: Get release version
      id: version
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Create release notes
      run: |
        echo "## Release ${{ steps.version.outputs.version }}" > RELEASE_NOTES.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> RELEASE_NOTES.md
    
    - name: Upload release notes
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: RELEASE_NOTES.md

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: release
    if: success()
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Build package
      run: |
        python -m pip install --upgrade pip build
        python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
    
    - name: Publish to GitHub Packages
      run: |
        pip install twine
        TWINE_USERNAME=${{ github.actor }} \
        TWINE_PASSWORD=${{ secrets.GITHUB_TOKEN }} \
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/*